apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pocketid
  namespace: pocketid
spec:
  releaseName: pocketid
  targetNamespace: pocketid
  chart:
    spec:
      chart: pocket-id
      sourceRef:
        kind: HelmRepository
        name: pocketid
        namespace: pocketid
  interval: 1h0m0s
  # values:
  #   pocketID:
  #     image:
  #       tag: v2
