apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pocketidp
  namespace: pocket-idp
spec:
  releaseName: pocketidp
  targetNamespace: pocket-idp
  chart:
    spec:
      chart: pocketidp
      sourceRef:
        kind: HelmRepository
        name: pocketidp-repo
        namespace: flux-system
  interval: 1h0m0s
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    replicaCount: 1
    image:
      repository: ghcr.io/pocketidp/pocketidp
      pullPolicy: IfNotPresent
      tag: latest
    service:
      type: ClusterIP
      port: 80
      targetPort: 8080
    gatewayApi:
      enabled: true
      gatewayName: envoy-gateway
      gatewayNamespace: envoy-gateway-system
      hostnames:
        - idp.homelab.larsmaes.nl
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 3
