---
apiVersion: v1
kind: Namespace
metadata:
  name: prom-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus
  namespace: prom-system
spec:
  interval: 24h
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: prom-system
spec:
  interval: 30m
  chart:
    spec:
      chart: prometheus
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: prom-system
      interval: 12h
  values:
    server:
      service:
        annotations: