---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: test-application
  namespace: test-application
spec:
  interval: 1h0m0s
  path: .
  prune: true
  sourceRef:
    kind: GitRepository
    name: test-application
  timeout: 3m0s
  wait: true