---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-controllers
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./fluxcd/infrastructure/controllers
  prune: true
  wait: true
  patches:
    - patch: |
        - op: add
          path: /spec/values/controller/service/annotations
          value: 
            metallb.io/loadBalancerIPs: 192.168.2.150
      target:
        kind: HelmRelease
        name: ingress-nginx
        namespace: ingress-nginx
    - patch: |
        - op: add
          path: /spec/values/server/service/annotations
          value: 
            metallb.io/loadBalancerIPs: 192.168.2.151
        - op: add
          path: /spec/values/server/service/type
          value: LoadBalancer
      target:
        kind: HelmRelease
        name: prometheus
        namespace: prom-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-configs
  namespace: flux-system
spec:
  # dependsOn:
  #   - name: infra-controllers
  interval: 10m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./fluxcd/infrastructure/configs
  prune: true
  patches:
    - patch: |
        - op: replace
          path: /spec/addresses
          value: 
            - "192.168.2.150-192.168.2.190"
      target:
        kind: IPAddressPool
        name: homelab-pool
