---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kro
  namespace: kro
spec:
  interval: 30m
  chart:
    spec:
      chart: kro
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: kro
        namespace: kro
      interval: 12h
  values:
    crds:
      enabled: true