apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  name: azure-resource-group
spec:
  api:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: 