apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  name: jenkins
spec:
  api:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: jenkins.marketplace.kratix.io
    spec:
      group: marketplace.kratix.io
      names:
        kind: jenkins
        plural: jenkins
        singular: jenkins
      scope: Namespaced
      versions:
      - name: v1alpha1
        schema:
          openAPIV3Schema:
            properties:
              spec:
                properties:
                  env:
                    default: dev
                    description: |
                      Configures and deploys this Jenkins with Environment specific configuration. Prod Jenkins comes with Backups pre-configured.
                    pattern: ^(dev|prod)$
                    type: string
                  plugins:
                    default: []
                    description: Plugins to install in the requested Jenkins
                    items:
                      description: Plugin defines a single Jenkins plugin.
                      properties:
                        downloadURL:
                          description: DownloadURL is the custom url from where plugin
                            has to be downloaded.
                          type: string
                        name:
                          description: Name is the name of Jenkins plugin
                          type: string
                        version:
                          description: Version is the version of Jenkins plugin
                          type: string
                      required:
                      - name
                      - version
                      type: object
                    type: array
                type: object
            type: object
        served: true
        storage: true
  destinationSelectors:
  - matchLabels:
      environment: dev
  workflows:
    promise:
      configure:
      - apiVersion: platform.kratix.io/v1alpha1
        kind: Pipeline
        metadata:
          name: promise-configure
        spec:
          containers:
          - image: ghcr.io/syntasso/kratix-marketplace/jenkins-configure-pipeline:v0.1.0
            name: jenkins-promise-pipeline
    resource:
      configure:
      - apiVersion: platform.kratix.io/v1alpha1
        kind: Pipeline
        metadata:
          name: instance-configure
        spec:
          containers:
          - image: ghcr.io/syntasso/kratix-marketplace/jenkins-configure-pipeline:v0.1.0
            name: jenkins-configure-pipeline