apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: app-yaml
  namespace: crossplane-system
spec:
  compositeTypeRef:
    apiVersion: example.larsmaes.nl/v1
    kind: App
  mode: Pipeline
  pipeline:
  - step: create-managed-resource
    functionRef:
      name: crossplane-contrib-function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      resources:
      - name: resource-group
        base:
          apiVersion: opentofu.upbound.io/v1beta1
          kind: Workspace
          metadata:
            name: example-rg
          spec:
            forProvider:
              source: Inline
              module: |
                variable "rg_name" {
                  type = string
                }

                variable "tags"
                {
                  type = map(string)
                  default = {}
                }

                resource "random_id" "rg" {
                  byte_length = 4
                }

                resource "azurerm_resource_group" "rg" {
                  name      = "rg-${var.rg_name}-${random_id.rg.hex}"
                  location  = "westeurope"
                  tags = merge(var.tags, {
                    managed-by = "crossplane"
                  })
                }
              vars:
              - key: "rg_name"
                value: "example"
              - key: "tags"
                value:
                  example.larsmaes.io/managed-by: crossplane
            providerConfigRef:
              name: azure-westeurope
        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: spec.forProvider.vars[0].value
        - type: FromCompositeFieldPath
          fromFieldPath: spec.tags
          toFieldPath: spec.forProvider.vars[1].value
        - type: FromCompositeFieldPath
          fromFieldPath: spec.tags
          toFieldPath: status.tags
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: metadata.labels[example.larsmaes.io/app]