apiVersion: azure.m.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  name: example-rg
  namespace: default
spec:
  forProvider:
    location: West Europe
  providerConfigRef:
    kind: ClusterProviderConfig
    name: default