apiVersion: v1
kind: Namespace
metadata:
  name: my-app
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: my-app
  namespace: flux-system
spec:
  interval: 0h1m0s
  path: ./fluxcd/apps/base/my-app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  dependsOn:
    - name: crossplane-system
  targetNamespace: my-app
  wait: true